In [1]:
import pandas as pd
import numpy as np
import pickle

path = "../../../../../../../../s/project/yeast_gxg/data/orthrus_data/"

In [2]:
protein_localization = np.load( path + 'protein_localization_dataset.npz')

print(protein_localization.files)

print("\nArray shapes:")
print(f"X shape: {protein_localization['X'].shape}")
print(f"y shape: {protein_localization['y'].shape}")
print(f"genes shape: {protein_localization['genes'].shape}")

print(f"\nX dtype: {protein_localization['X'].dtype}")
print(f"y dtype: {protein_localization['y'].dtype}")
print(f"genes dtype: {protein_localization['genes'].dtype}")

print(f"\nFirst few y values: {protein_localization['y'][:10]}")
print(f"First few genes: {protein_localization['genes'][:10]}")

print(f"\nX dimensions: {protein_localization['X'].ndim}")
if protein_localization['X'].ndim == 3:
    print(f"X first sample shape: {protein_localization['X'][0].shape}")
    print(f"X first sample, first feature vector: {protein_localization['X'][0, 0, :5]}")  # First 5 features
elif protein_localization['X'].ndim == 2:
    print(f"X first sample (first 10 features): {protein_localization['X'][0, :10]}")

print(f"\nUnique y values: {np.unique(protein_localization['y'])}")
print(f"Number of classes: {len(np.unique(protein_localization['y']))}")

['X', 'y', 'genes']

Array shapes:
X shape: (9769, 12288, 6)
y shape: (9769, 12)
genes shape: (9769,)

X dtype: float32
y dtype: float32
genes dtype: <U15

First few y values: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
First few genes: ['C1orf112' 'FGR' 'CFH' 'GCLC' 'NFYA' 'STPG1' 'NIPAL3' 'ANKIB1' 'CYP51A1'
 'KRIT1']

X dimensions: 3
X first sample shape: (12288, 6)
X first sample, first feature vector: [0. 0. 1. 0. 0.]

Unique y values: [0. 1.]
Number of classes: 2
